# Generated by Django 5.2.9 on 2025-12-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='anio',
            field=models.IntegerField(default=2025, verbose_name='Año Tributario'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='razon_social',
            field=models.CharField(default='Sin Nombre', max_length=255, verbose_name='Razón Social'),
        ),
    ]
