# Generated by Django 5.2.9 on 2025-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calificaciontributaria_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='factor',
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='ejercicio',
            field=models.IntegerField(default=2025, verbose_name='Ejercicio (Año)'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_10',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 10'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_11',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 11'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_12',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 12'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_13',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 13'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_14',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 14'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_15',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 15'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_16',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 16'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_8',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 8'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_9',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor 9'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='instrumento',
            field=models.CharField(default='GENERICO', max_length=50, verbose_name='Instrumento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='mercado',
            field=models.CharField(default='GENERICO', max_length=10, verbose_name='Mercado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='numero_dividendo',
            field=models.BigIntegerField(default=0, verbose_name='N° Dividendo'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='secuencia',
            field=models.BigIntegerField(default=0, verbose_name='Secuencia'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='tipo_sociedad',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Histórico'),
        ),
    ]
