# Generated by Django 5.2.9 on 2025-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_calificaciontributaria_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_17',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_18',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_19',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_20',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_21',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_22',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_23',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_24',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_25',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_26',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_27',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_28',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_29',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_30',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_31',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_32',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_33',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_34',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_35',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_36',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_37',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_10',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_11',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_12',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_13',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_14',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_15',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_16',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_8',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_9',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='tipo_sociedad',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', max_length=1, verbose_name='Tipo Sociedad'),
        ),
    ]
