# Generated by Django 5.2.9 on 2025-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calificaciontributaria_factor_17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='es_isfut',
            field=models.BooleanField(default=False, verbose_name='Acogido a ISFUT'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Factor Actualización'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='origen',
            field=models.CharField(default='MANUAL', max_length=20, verbose_name='Origen de Datos'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='ejercicio',
            field=models.IntegerField(default=2025, verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='tipo_sociedad',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
