# Generated by Django 5.2.8 on 2025-12-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calificaciontributaria_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='es_isfut',
        ),
    ]
